name: Publish to npm on Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Extract Release Version
        id: extract-version
        run: |
          # Extract the release version from the GITHUB_REF
          export RELEASE_VERSION=$(echo $GITHUB_REF | sed 's#refs/tags/##')

      - name: Update Package Version
        run: |
          # Use the extracted release version to update the package.json
          npm version $RELEASE_VERSION

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish
